CREATE TABLE IF NOT EXISTS Users (
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  fullname TEXT NOT NULL,
  age INTEGER,
  sex TEXT,
  dog_name TEXT,
  dog_breed TEXT,
  dog_sex TEXT,
  time_created DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS Matches (
  match_id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id1 INTEGER NOT NULL,
  user_id2 INTEGER NOT NULL,
  time_created DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id1, user_id2),
  FOREIGN KEY (user_id1) REFERENCES Users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (user_id2) REFERENCES Users(user_id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS AuthUsers (
  auth_user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  time_created DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

ALTER TABLE Users ADD COLUMN photo_url TEXT;